### ISSUE TITLE
Functional - My Profile Screen - 

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#18]
For the “Division/Region” wouldn’t it be easier to have a drop-down list the division and region names or make them two fields. Doing so will prevent issues of misspelled responses. Also, does it matter what division or region a person is in when they spot an issue in or around the building that is not part of their division or region? An example would be a person could be in the cafeteria and report a mess.

**Comment by aanthonyDOL** [comment]
There are a requirement per the client to have user fill this information out. In a later MVP there may be an option to add the division/regions as drop-down.

**Comment by jfc3-dol** [comment]
Okay, makes sense so I will close the issue.
