### ISSUE TITLE
Functional - My Profile Screen - Make State Input Field a Drop-down List

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#22]
It would be easier to have a list of states and other locations (Unites States Territories) as a drop-down list so there are less spelling issues and people can find the right one easier.

**Comment by aanthonyDOL** [comment]
Per the requirements , these are plain text-fields. There maybe future enhancements to make this field a drop-down list.

**Comment by jfc3-dol** [comment]
If that is the case, for now, I will close the issue.
