### ISSUE TITLE
Accessibility - Resources Screen - Poor Color Contrast for Green Text

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#23]
There is not enough color contrast with the green “National Office” text ( #49A564 ) and the white background ( #ffffff ). The color contrast ratio is 3.07:1 and needs to be 4.5:1 or higher to pass. 

Please see attached screenshot.

![safetynet - resources screen - poor color contrast for green national office text](https://user-images.githubusercontent.com/10423487/61550747-4d5b9100-aa21-11e9-9a40-c7712c09fe45.png)

**Comment by aanthonyDOL** [comment]
Have to follow up

**Comment by jfc3-dol** [comment]
If you use you the darker green (#004D00), you mentioned in another issue that would pass color contrast.

**Comment by aanthonyDOL** [comment]
Changed to darker green (#004D00) fixed

**Comment by jfc3-dol** [comment]
@aanthonyDOL,
The green heading text ( #478347 ) now has a color contrast ratio of 4.56:1 and passes. So I'm going to close this issue from my perspective.
