### ISSUE TITLE
Functional - Resources Screen - Address Punctuation Needs Fixes

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#24]
For the second line of the address, a comma is needed after “Washington” along with a period after in the “D.C” or remove the first one.

Please see the attached screenshot.

![safetynet - resources screen - missing comma and period in address section of scren](https://user-images.githubusercontent.com/10423487/61551067-2a7dac80-aa22-11e9-83ec-5942cb5ac257.png)

**Comment by aanthonyDOL** [comment]
Fixed

**Comment by jfc3-dol** [comment]
@aanthonyDOL,

Thanks for adding the comma after the word "Washington" and a period after the "C" in "D.C." and because of that, I'm closing the issue.

Please see the attached screenshot.

![safetynet - resources screen - punctuation has been corrected for Washington DC](https://user-images.githubusercontent.com/10423487/62654703-5fe52e00-b92e-11e9-84b4-e927f0700dab.png)
