### ISSUE TITLE
Functional - Resources Screen - DOL Link Missing "S" Where It Should Be HTTPS Instead of HTTP

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#28]
The first DOL.gov link needs to be corrected and use HTTPS since it’s a secure website. Currently, it is missing an "S" at least on the visual presentation, but please check the link code too.

Please see the attached screenshot.

![safetynet - resources screen - link missing an S  as in the link below should be https](https://user-images.githubusercontent.com/10423487/61553718-112c2e80-aa29-11e9-8861-fc1713637929.png)

**Comment by aanthonyDOL** [comment]
Fixed

**Comment by jfc3-dol** [comment]
All the links are now HTTPS, so I'm going to close this issue.

Please see the attached screenshot.

![safetynet - resources screen - all the links are now HTTPS](https://user-images.githubusercontent.com/10423487/62653735-2e6b6300-b92c-11e9-8f8e-0facc10257c8.png)
