### ISSUE TITLE
Functional - DOL Contacts Screen - Text Alignment Issue with Main Content Section

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#34]
I am wondering why the e-mail address and phone number do not align with the text above it?

Please see the attached screenshot.

![safetynet - dol contacts screen - why is this text not aligned with the other above it](https://user-images.githubusercontent.com/10423487/61558519-49d20500-aa35-11e9-82ca-98f7299c80e6.png)

**Comment by aanthonyDOL** [comment]
Fixed

**Comment by jfc3-dol** [comment]
The e-mail address and phone number text are now aligned with the other text above it, and because the issue is corrected, I'm closing the issue.

Please see the attached screenshot.

![safetynet - dol contacts screen - e-mail address and phone number ext are now aligned with the other text above it](https://user-images.githubusercontent.com/10423487/62648383-ac297180-b920-11e9-9b21-5f42ea6248a1.png)
