### ISSUE TITLE
Accessibility - DOL Contacts Screen - Links Not Underlined to Know They are Links

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#35]
The e-mail address should have an underline so the user knows it is a link that can be tapped/clicked. If the phone number can be used to call, it should have an underline too.

Please see the attached screenshot.

![safetynet - dol contacts screen - e-mail addrss and phone number need underline to tell users they are links](https://user-images.githubusercontent.com/10423487/61558751-e1375800-aa35-11e9-9764-edc6bb68de55.png)

**Comment by aanthonyDOL** [comment]
Fixed.

**Comment by jfc3-dol** [comment]
The e-mail address and phone number each have an underline to them now on the "Contacts" screen so the user knows they are links and can be tapped.

Because the issue is corrected, I'm closing the issue.

Please see the attached screenshot.

![safetynet - dol contacts screen - e-mail addrss and phone number now have an underline to tell users they are links](https://user-images.githubusercontent.com/10423487/62648151-2d343900-b920-11e9-89ea-3213957591ed.png)
