### ISSUE TITLE
Accessibility - My Incidents Screen - Focus Not Set to Top of Screen

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#39]
Once the user taps on the “My Incidents” link/tab in the footer section of the screen, I would expect to be focused at the top of the screen instead of staying at the bottom of the screen on the "My Incidents" link/tab.

**Comment by aanthonyDOL** [comment]
When the user clicks the My Incidents tab the focus is on the Menu button at the top of the page. Is this the behavior you are referring to?

**Comment by jfc3-dol** [comment]
Yes, in this application, I would expect the focus to go the Menu button at the top of the application, which would be similar for other pages that have the same issue.

**Comment by jfc3-dol** [comment]
@aanthonyDOL,

Now when I tap the "My Incidents" button in the footer VoiceOver focuses on the add "Photo" button which I believe was that last field I was using while testing that I could add photos with VoiceOver running.

But after focusing on other fields and leaving the screen and coming back as an anonymous and non-anonymous user, the focus goes to the "Menu" button.

So I'm going to close the issue, and if it reappears, I can reopen it or create a new one.
