### ISSUE TITLE
Accessibiltiy -  Submit Screen - VoiceOver Reading Photo Field as Required when Not Marked that Way

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#41]
VoiceOver is reading the “Photo” item as a required field when it is not marked visually as a required field.

**Comment by aanthonyDOL** [comment]
Fixed. Photo Field isn't required.

**Comment by jfc3-dol** [comment]
VoiceOver is no longer reading the "Photo" field as being "Required", so I'm going to close the issue since it's working as expected.
