### ISSUE TITLE
Functional - Submit Screen - Why is Garage Section, Floor, and Closest Room Number Required

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#42]
Why is the “Garage Section” a required field when most people aren’t going to have any issues to report from the garage? Same applies to the “Floor” and “Closest Room #” being required in case a person is in the garage or outside the building.

Please see the attached screenshots.

**Screenshot showing floor and room number being required.**

![safetynet - anonymous incident screen - why are the floor and room required when a person could be outside or in garage](https://user-images.githubusercontent.com/10423487/61561830-e698a080-aa3d-11e9-8625-6153a9395ca0.png)

**Screenshot showing garage section being required.**

![safetynet - anonymous incident screen - why are the garage section required if the person is outside or on a floor in the building](https://user-images.githubusercontent.com/10423487/61561851-f1ebcc00-aa3d-11e9-9c44-68f2ec5ad2bd.png)

**Comment by aanthonyDOL** [comment]
Per our Requirements , these are Required Fields.

**Comment by jfc3-dol** [comment]
Okay, will close issue but it doesn't seem right to make them required if they don't apply all the time.
