### ISSUE TITLE
Accessibility - Submit Screen - VoiceOver User Not Able to Add Photo

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#44]
VoiceOver didn’t read anything for the “Upload Image” area after reading the text before it and then went to the “Region” text/LABEL. The VoiceOver needs to be able to take a photo or grab one from their camera roll.

**Comment by aanthonyDOL** [comment]
Added functionality for VoiceOver to upload image.

**Comment by jfc3-dol** [comment]
Thanks, will test in the next version of the application.

**Comment by jfc3-dol** [comment]
VoiceOver user is now able to take and add a photo to an incident, so I'm going to close the issue because it's working as expected now.
