### ISSUE TITLE
Accessibility - Submit Screen - Can Not Submit Photo with VoiceOver

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#50]
With VoiceOver on, there is no way to take a photo or grab one from my library/camera roll. If I turn VoiceOver off, I can then add a photo to my incident. It should work for anyone even if they are using VoiceOver or not.

**Comment by aanthonyDOL** [comment]
Added VoiceOver for Image

**Comment by jfc3-dol** [comment]
Now able to take photo using VoiceOver, so I'm going to close the issue.
