### ISSUE TITLE
Functional - Submit Screen - There are Three Input Fields I Can Not Enter Information

### ISSUE THREAD

**Issue by jfc3-dol** [USDepartmentofLabor/OCIO-DOLSafety-iOS#51]
The user is not able to enter information in the “Region”, Safety and Health Manager”, or Building” fields using VoiceOver or even if they are not. Is that because I have been assigned those fields because of where I work? If I’m in another office in the same city, I work in or somewhere else I might want to submit an item, and that information might be different.

**Comment by aanthonyDOL** [comment]
This is by design for the MVP 1. As we progress to later MVP's we will expand the app's user base to other locations. As of now the user base is currently Francis Perkins Building, with the assigned region and Safety&Health Manager.

**Comment by jfc3-dol** [comment]
Okay, that makes sense so I will close this issue.
